### ISSUE TITLE
Improve biome module

### ISSUE THREAD

**Issue by aksiome** [Gunivers/Bookshelf#141]
## Tasks
- [ ] Use a generator to generate everything
- [ ] Get biome string id, and maybe other interesting data, see generated format (https://github.com/misode/mcmeta/blob/1.20.4-summary/data/worldgen/biome/data.jsone)
- [ ] Change output to storage (maybe a single command that returns all the useful data is preferable)
- [ ] If possible get temperature noise to compute the exact temperature
- [ ] Write tests
