### ISSUE TITLE
Add hex color conversion

### ISSUE THREAD

**Issue by aksiome** [Gunivers/Bookshelf#142]
## Tasks
- [x] Add `#bs.color:hex_to_int`
- [x] Add `#bs.color:int_to_hex`
- [x] Add `#bs.color:hex_to_rgb`
- [x] Add `#bs.color:rgb_to_hex`
