### ISSUE TITLE
Write examples for modules

### ISSUE THREAD

**Issue by aksiome** [Gunivers/Bookshelf#147]
## Tasks
- [ ] Gravity Gun (block, move)
- [ ] Portal Gun ? (move, raycast, id)
- [ ] Imprimante 3D (block)
- [ ] TnT réaliste (move)
- [ ] Painting -> change block color whithout changing block type, nbt and blockstate (block)
- [ ] Lance peinture + charge de peinture en XP bar (move + xp)
- [ ] Life string -> effet négatif synchronisant la vie de 2 entités (health)
- [ ] Balle rebondissante (move)
