### ISSUE TITLE
Simplify UUID usage and harmonise force loaded chunks

### ISSUE THREAD

**Issue by aksiome** [Gunivers/Bookshelf#153]
## Tasks
- [x] ~Use the new selector module to return a string selector (player name or entity string UUID) instead of an UUID array.~
- [x] Use the new B5-0-0-0-4 persistent entity pointer with uuid array instead of the selector module (keep targeted_entity and change the view module)
- [x] Move every persistent entity to the only chunk that should be forceloaded (-30000000 1600)
- [x] Edit contribution doc to add new entity and which chunk should be forceloaded

Updated modules:
- [x] hitbox
- [x] math
- [x] move
- [x] position
- [x] raycast
- [x] schedule
- [x] sidebar
- [x] vector
- [x] view
