### ISSUE TITLE
Rework `bs.hitbox`, `bs.raycast`, and `bs.move` interfaces

### ISSUE THREAD

**Issue by aksiome** [Gunivers/Bookshelf#172]
## Tasks
- [x] Delete `bs.width` & `bs.height` objectives (`bs.hitbox`)
- [x] Inline bitwise operations to avoid dependencies (`bs.hitbox`)
- [x] Inline distance computation to avoid dependencies (`bs.view`)
- [x] RAYCAST Use ignored_entities with entity type tag instead of the is_solid tag and add an optional tag to filter entities.
- [x] MOVE Use ignored_entities with entity type tag instead of the is_solid tag and add an optional tag to filter entities.
- [x] RAYCAST Using the input storage as a config can lead to undesirable side effects. Replace this by a macro var (`with`) with optional values.
- [x] MOVE Using the input storage as a config can lead to undesirable side effects. Replace this by a macro var (`with`) with optional values.
